set(_adobe_roots "")
if(DEFINED ENV{ADOBE_AE_SDK_ROOT})
    list(APPEND _adobe_roots "$ENV{ADOBE_AE_SDK_ROOT}")
endif()
if(DEFINED ENV{ADOBE_PREMIERE_SDK_ROOT})
    list(APPEND _adobe_roots "$ENV{ADOBE_PREMIERE_SDK_ROOT}")
endif()

set(ADOBE_SDK_FOUND FALSE)
foreach(_root IN LISTS _adobe_roots)
    if(EXISTS "${_root}/Examples/Headers" OR EXISTS "${_root}/Headers")
        set(ADOBE_SDK_FOUND TRUE)
        set(ADOBE_SDK_ROOT "${_root}")
        if(EXISTS "${_root}/Examples/Headers")
            set(ADOBE_SDK_INCLUDE_DIRS "${_root}/Examples/Headers")
        else()
            set(ADOBE_SDK_INCLUDE_DIRS "${_root}/Headers")
        endif()
        break()
    endif()
endforeach()

